const PDFDocument = require("pdfkit");
const ExcelJS     = require("exceljs");
const Attendance  = require("../models/Attendance");
const User        = require("../models/User");
const logger      = require("../config/logger");


const fmtMins = (mins = 0) => {
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
};


const fmtTime = (d) =>
  d
    ? new Date(d).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: true })
    : "—";

const fmtDate = (d) =>
  d ? new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";


const buildFilter = async (req) => {
  const { startDate, endDate, userId } = req.query;
  if (!startDate || !endDate) {
    throw new Error("startDate and endDate are required");
  }

  const filter = { date: { $gte: startDate, $lte: endDate } };

  if (req.user.role === "employee") {
    filter.userId = req.user._id;
  } else if (req.user.role === "manager") {
    const team    = await User.find({ managerId: req.user._id }).select("_id");
    const teamIds = team.map((u) => u._id);
    filter.userId = userId ? userId : { $in: teamIds };
  } else {
    if (userId) filter.userId = userId;
  }

  return filter;
};


const downloadPDF = async (req, res) => {
  try {
    const filter  = await buildFilter(req);
    const records = await Attendance.find(filter)
      .populate("userId", "name email department role")
      .sort({ date: -1 });

    const { startDate, endDate } = req.query;


    const doc = new PDFDocument({ margin: 40, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="attendance_${startDate}_to_${endDate}.pdf"`
    );
    doc.pipe(res);

   
    doc
      .rect(0, 0, doc.page.width, 70)
      .fill("#4f46e5");

    doc
      .fillColor("#ffffff")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text("AttendPro", 40, 20);

    doc
      .font("Helvetica")
      .fontSize(10)
      .text("Attendance Management System", 40, 46);

    doc
      .fillColor("#a5b4fc")
      .fontSize(9)
      .text(`Report Period: ${startDate}  →  ${endDate}`, 40, 56);

    doc.moveDown(3);

   
    const summaryY = 90;
    doc
      .roundedRect(40, summaryY, doc.page.width - 80, 55, 6)
      .fillAndStroke("#f8f9ff", "#e0e7ff");

    const present   = records.filter((r) => r.status !== "absent").length;
    const completed = records.filter((r) => r.status === "completed").length;
    const totalMins = records.reduce((a, r) => a + (r.totalWorkingMinutes || 0), 0);

    doc.fillColor("#1e1b4b").font("Helvetica-Bold").fontSize(9);
    doc.text(`Total Records: ${records.length}`,     55, summaryY + 12);
    doc.text(`Present Days: ${present}`,             55, summaryY + 26);
    doc.text(`Completed Shifts: ${completed}`,       55, summaryY + 40);
    doc.text(`Total Hours Logged: ${fmtMins(totalMins)}`, 250, summaryY + 12);
    doc.text(`Generated On: ${new Date().toLocaleDateString("en-IN")}`, 250, summaryY + 26);
    doc.text(`Generated By: ${req.user.name}`,       250, summaryY + 40);

    doc.moveDown(4);


    const tableTop  = 165;
    const colWidths = [70, 115, 65, 65, 65, 65, 60]; // date, name, dept, in, out, hours, status
    const headers   = ["Date", "Employee", "Dept", "Punch In", "Punch Out", "Hours", "Status"];
    const startX    = 40;


    doc.rect(startX, tableTop, doc.page.width - 80, 20).fill("#4f46e5");
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(8);

    let colX = startX + 4;
    headers.forEach((h, i) => {
      doc.text(h, colX, tableTop + 6, { width: colWidths[i] - 4, align: "left" });
      colX += colWidths[i];
    });


    let rowY = tableTop + 20;
    records.forEach((rec, idx) => {
   
      if (idx % 2 === 0) {
        doc.rect(startX, rowY, doc.page.width - 80, 18).fill("#f5f3ff");
      }

      const statusColor =
        rec.status === "completed"  ? "#059669" :
        rec.status === "incomplete" ? "#d97706" :
        rec.status === "present"    ? "#2563eb" : "#6b7280";

      doc.fillColor("#1f2937").font("Helvetica").fontSize(7.5);

      colX = startX + 4;
      const rowData = [
        rec.date,
        rec.userId?.name || "—",
        rec.userId?.department || "—",
        fmtTime(rec.punchIn?.time),
        fmtTime(rec.punchOut?.time),
        fmtMins(rec.totalWorkingMinutes),
      ];

      rowData.forEach((val, i) => {
        doc.fillColor("#1f2937").text(String(val), colX, rowY + 5, {
          width: colWidths[i] - 4,
          align: "left",
          lineBreak: false,
        });
        colX += colWidths[i];
      });

  
      doc.fillColor(statusColor).font("Helvetica-Bold").text(rec.status, colX, rowY + 5, {
        width: colWidths[6] - 4,
        align: "left",
      });

    
      doc.moveTo(startX, rowY + 18).lineTo(startX + doc.page.width - 80, rowY + 18)
        .strokeColor("#e5e7eb").lineWidth(0.3).stroke();

      rowY += 18;

   
      if (rowY > doc.page.height - 80) {
        doc.addPage();
        rowY = 40;
      }
    });


    const footerY = doc.page.height - 40;
    doc
      .moveTo(40, footerY - 5).lineTo(doc.page.width - 40, footerY - 5)
      .strokeColor("#e0e7ff").lineWidth(0.5).stroke();

    doc
      .fillColor("#6b7280")
      .font("Helvetica")
      .fontSize(8)
      .text("Generated by AttendPro — Attendance Management System", 40, footerY, {
        align: "center",
        width: doc.page.width - 80,
      });

    doc.end();
    logger.info(`PDF report downloaded by ${req.user.email} | ${records.length} records`);
  } catch (error) {
    logger.error(`PDF report error: ${error.message}`);
    if (!res.headersSent) {
      res.status(error.message.includes("required") ? 400 : 500).json({
        success: false,
        message: error.message || "Failed to generate PDF",
      });
    }
  }
};


const downloadExcel = async (req, res) => {
  try {
    const filter  = await buildFilter(req);
    const records = await Attendance.find(filter)
      .populate("userId", "name email department role")
      .sort({ date: -1 });

    const { startDate, endDate } = req.query;

    const workbook  = new ExcelJS.Workbook();
    workbook.creator = "AttendPro";
    workbook.created = new Date();

    const sheet = workbook.addWorksheet("Attendance Report", {
      pageSetup: { paperSize: 9, orientation: "landscape" },
    });


    sheet.columns = [
      { header: "Date",           key: "date",         width: 14 },
      { header: "Employee Name",  key: "name",         width: 22 },
      { header: "Email",          key: "email",        width: 28 },
      { header: "Department",     key: "department",   width: 18 },
      { header: "Role",           key: "role",         width: 12 },
      { header: "Punch In",       key: "punchIn",      width: 14 },
      { header: "Punch Out",      key: "punchOut",     width: 14 },
      { header: "Working Hours",  key: "hours",        width: 16 },
      { header: "Status",         key: "status",       width: 14 },
      { header: "OT Requested",   key: "otRequested",  width: 14 },
      { header: "OT Status",      key: "otStatus",     width: 14 },
      { header: "OT Minutes",     key: "otMinutes",    width: 14 },
      { header: "Punch-In Lat",   key: "lat",          width: 16 },
      { header: "Punch-In Lng",   key: "lng",          width: 16 },
    ];


    const headerRow = sheet.getRow(1);
    headerRow.eachCell((cell) => {
      cell.fill   = { type: "pattern", pattern: "solid", fgColor: { argb: "FF4F46E5" } };
      cell.font   = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
      cell.border = {
        bottom: { style: "thin", color: { argb: "FF3730A3" } },
      };
      cell.alignment = { vertical: "middle", horizontal: "center" };
    });
    headerRow.height = 24;


    const STATUS_COLORS = {
      completed:  "FFD1FAE5",
      incomplete: "FFFEF3C7",
      present:    "FFDBEAFE",
      absent:     "FFF3F4F6",
    };

    records.forEach((rec, idx) => {
      const row = sheet.addRow({
        date:        rec.date,
        name:        rec.userId?.name        || "—",
        email:       rec.userId?.email       || "—",
        department:  rec.userId?.department  || "—",
        role:        rec.userId?.role        || "—",
        punchIn:     fmtTime(rec.punchIn?.time),
        punchOut:    fmtTime(rec.punchOut?.time),
        hours:       fmtMins(rec.totalWorkingMinutes),
        status:      rec.status,
        otRequested: rec.overtimeRequested ? "Yes" : "No",
        otStatus:    rec.overtimeStatus    || "—",
        otMinutes:   rec.overtimeMinutes   || 0,
        lat:         rec.punchIn?.location?.latitude  || "—",
        lng:         rec.punchIn?.location?.longitude || "—",
      });

 
      const bgColor = STATUS_COLORS[rec.status] || "FFFFFFFF";
      row.eachCell((cell) => {
        cell.fill      = { type: "pattern", pattern: "solid", fgColor: { argb: bgColor } };
        cell.alignment = { vertical: "middle", horizontal: "center" };
        cell.border    = {
          bottom: { style: "hair", color: { argb: "FFE5E7EB" } },
        };
      });
      row.height = 20;
    });


    const summarySheet = workbook.addWorksheet("Summary");
    summarySheet.columns = [
      { header: "Metric", key: "metric", width: 30 },
      { header: "Value",  key: "value",  width: 20 },
    ];

    const present   = records.filter((r) => r.status !== "absent").length;
    const completed = records.filter((r) => r.status === "completed").length;
    const totalMins = records.reduce((a, r) => a + (r.totalWorkingMinutes || 0), 0);

    [
      ["Report Period",    `${startDate} to ${endDate}`],
      ["Generated By",     req.user.name],
      ["Generated At",     new Date().toLocaleString("en-IN")],
      ["Total Records",    records.length],
      ["Present Days",     present],
      ["Completed Shifts", completed],
      ["Total Hours",      fmtMins(totalMins)],
    ].forEach(([metric, value]) => {
      summarySheet.addRow({ metric, value });
    });

    summarySheet.getRow(1).font = { bold: true };

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="attendance_${startDate}_to_${endDate}.xlsx"`
    );

    await workbook.xlsx.write(res);
    res.end();

    logger.info(`Excel report downloaded by ${req.user.email} | ${records.length} records`);
  } catch (error) {
    logger.error(`Excel report error: ${error.message}`);
    if (!res.headersSent) {
      res.status(error.message.includes("required") ? 400 : 500).json({
        success: false,
        message: error.message || "Failed to generate Excel",
      });
    }
  }
};

module.exports = { downloadPDF, downloadExcel };
